name: "base"  # name must keep consistant with folder name
backend: "python"
max_batch_size: 16

input [
    {
        name: "INPUT0"
        data_type: TYPE_FLOAT32
        dims: [ 1 ]
    }
]

output [
    {
        name: "OUTPUT0"
        data_type:TYPE_FLOAT32
        dims:[ 1 ]
    }
]
